title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

  sandbox:
    width: 1/1
    sections:
      morefields:
        type: fields
        fields:
          accordion:
            extends: fields/accordion
            label: List

          layout:
            label: Banana
            extends: fields/layout
